# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiDesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1372, 755)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("uiComponents/uiLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidgetTest = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidgetTest.setGeometry(QtCore.QRect(0, 0, 1371, 751))
        self.tabWidgetTest.setMinimumSize(QtCore.QSize(401, 0))
        self.tabWidgetTest.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidgetTest.setMovable(True)
        self.tabWidgetTest.setObjectName("tabWidgetTest")
        self.tabTestPhase = QtWidgets.QWidget()
        self.tabTestPhase.setObjectName("tabTestPhase")
        self.labelImageContainer = QtWidgets.QLabel(self.tabTestPhase)
        self.labelImageContainer.setGeometry(QtCore.QRect(10, 10, 1121, 661))
        self.labelImageContainer.setAutoFillBackground(True)
        self.labelImageContainer.setText("")
        self.labelImageContainer.setObjectName("labelImageContainer")
        self.groupBoxPrediction = QtWidgets.QGroupBox(self.tabTestPhase)
        self.groupBoxPrediction.setGeometry(QtCore.QRect(1140, 0, 211, 321))
        self.groupBoxPrediction.setStyleSheet("")
        self.groupBoxPrediction.setObjectName("groupBoxPrediction")
        self.labelGradePrediction1 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePrediction1.setGeometry(QtCore.QRect(20, 30, 111, 31))
        self.labelGradePrediction1.setAutoFillBackground(True)
        self.labelGradePrediction1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePrediction1.setObjectName("labelGradePrediction1")
        self.labelGradePercentage1 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePercentage1.setGeometry(QtCore.QRect(130, 30, 61, 31))
        self.labelGradePercentage1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelGradePercentage1.setToolTipDuration(-1)
        self.labelGradePercentage1.setAutoFillBackground(True)
        self.labelGradePercentage1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePercentage1.setObjectName("labelGradePercentage1")
        self.labelGradePrediction2 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePrediction2.setGeometry(QtCore.QRect(20, 70, 111, 31))
        self.labelGradePrediction2.setAutoFillBackground(True)
        self.labelGradePrediction2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePrediction2.setObjectName("labelGradePrediction2")
        self.labelGradePercentage2 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePercentage2.setGeometry(QtCore.QRect(130, 110, 61, 31))
        self.labelGradePercentage2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelGradePercentage2.setToolTipDuration(-1)
        self.labelGradePercentage2.setAutoFillBackground(True)
        self.labelGradePercentage2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePercentage2.setObjectName("labelGradePercentage2")
        self.labelGradePrediction3 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePrediction3.setGeometry(QtCore.QRect(20, 110, 111, 31))
        self.labelGradePrediction3.setAutoFillBackground(True)
        self.labelGradePrediction3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePrediction3.setObjectName("labelGradePrediction3")
        self.labelGradePercentage3 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePercentage3.setGeometry(QtCore.QRect(130, 70, 61, 31))
        self.labelGradePercentage3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelGradePercentage3.setToolTipDuration(-1)
        self.labelGradePercentage3.setAutoFillBackground(True)
        self.labelGradePercentage3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePercentage3.setObjectName("labelGradePercentage3")
        self.labelGradePrediction4 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePrediction4.setGeometry(QtCore.QRect(20, 150, 111, 31))
        self.labelGradePrediction4.setAutoFillBackground(True)
        self.labelGradePrediction4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePrediction4.setObjectName("labelGradePrediction4")
        self.labelGradePercentage4 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePercentage4.setGeometry(QtCore.QRect(130, 150, 61, 31))
        self.labelGradePercentage4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelGradePercentage4.setToolTipDuration(-1)
        self.labelGradePercentage4.setAutoFillBackground(True)
        self.labelGradePercentage4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePercentage4.setObjectName("labelGradePercentage4")
        self.labelGradePrediction5 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePrediction5.setGeometry(QtCore.QRect(20, 190, 111, 31))
        self.labelGradePrediction5.setAutoFillBackground(True)
        self.labelGradePrediction5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePrediction5.setObjectName("labelGradePrediction5")
        self.labelGradePrediction6 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePrediction6.setGeometry(QtCore.QRect(20, 230, 111, 31))
        self.labelGradePrediction6.setAutoFillBackground(True)
        self.labelGradePrediction6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePrediction6.setObjectName("labelGradePrediction6")
        self.labelGradePercentage5 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePercentage5.setGeometry(QtCore.QRect(130, 190, 61, 31))
        self.labelGradePercentage5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelGradePercentage5.setToolTipDuration(-1)
        self.labelGradePercentage5.setAutoFillBackground(True)
        self.labelGradePercentage5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePercentage5.setObjectName("labelGradePercentage5")
        self.labelGradePercentage6 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePercentage6.setGeometry(QtCore.QRect(130, 230, 61, 31))
        self.labelGradePercentage6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelGradePercentage6.setToolTipDuration(-1)
        self.labelGradePercentage6.setAutoFillBackground(True)
        self.labelGradePercentage6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePercentage6.setObjectName("labelGradePercentage6")
        self.labelGradePrediction7 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePrediction7.setGeometry(QtCore.QRect(20, 270, 111, 31))
        self.labelGradePrediction7.setAutoFillBackground(True)
        self.labelGradePrediction7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePrediction7.setObjectName("labelGradePrediction7")
        self.labelGradePercentage7 = QtWidgets.QLabel(self.groupBoxPrediction)
        self.labelGradePercentage7.setGeometry(QtCore.QRect(130, 270, 61, 31))
        self.labelGradePercentage7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.labelGradePercentage7.setToolTipDuration(-1)
        self.labelGradePercentage7.setAutoFillBackground(True)
        self.labelGradePercentage7.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradePercentage7.setObjectName("labelGradePercentage7")
        self.groupBoxCommandButton = QtWidgets.QGroupBox(self.tabTestPhase)
        self.groupBoxCommandButton.setGeometry(QtCore.QRect(1140, 400, 211, 321))
        self.groupBoxCommandButton.setObjectName("groupBoxCommandButton")
        self.pushButtonLoadImageFile = QtWidgets.QPushButton(self.groupBoxCommandButton)
        self.pushButtonLoadImageFile.setGeometry(QtCore.QRect(40, 20, 121, 31))
        self.pushButtonLoadImageFile.setObjectName("pushButtonLoadImageFile")
        self.pushButtonPredictImageFile = QtWidgets.QPushButton(self.groupBoxCommandButton)
        self.pushButtonPredictImageFile.setGeometry(QtCore.QRect(50, 60, 101, 31))
        self.pushButtonPredictImageFile.setAutoDefault(False)
        self.pushButtonPredictImageFile.setDefault(False)
        self.pushButtonPredictImageFile.setFlat(False)
        self.pushButtonPredictImageFile.setObjectName("pushButtonPredictImageFile")
        self.spinBoxLayerNum = QtWidgets.QSpinBox(self.groupBoxCommandButton)
        self.spinBoxLayerNum.setGeometry(QtCore.QRect(110, 140, 71, 22))
        self.spinBoxLayerNum.setMaximum(30)
        self.spinBoxLayerNum.setObjectName("spinBoxLayerNum")
        self.pushButtonShowFMs = QtWidgets.QPushButton(self.groupBoxCommandButton)
        self.pushButtonShowFMs.setGeometry(QtCore.QRect(30, 170, 151, 31))
        self.pushButtonShowFMs.setObjectName("pushButtonShowFMs")
        self.labelLNo = QtWidgets.QLabel(self.groupBoxCommandButton)
        self.labelLNo.setGeometry(QtCore.QRect(30, 140, 81, 21))
        self.labelLNo.setObjectName("labelLNo")
        self.pushButtonShowFM = QtWidgets.QPushButton(self.groupBoxCommandButton)
        self.pushButtonShowFM.setGeometry(QtCore.QRect(30, 240, 151, 31))
        self.pushButtonShowFM.setObjectName("pushButtonShowFM")
        self.spinBoxFMNum = QtWidgets.QSpinBox(self.groupBoxCommandButton)
        self.spinBoxFMNum.setGeometry(QtCore.QRect(140, 210, 51, 22))
        self.spinBoxFMNum.setMaximum(130)
        self.spinBoxFMNum.setProperty("value", 0)
        self.spinBoxFMNum.setObjectName("spinBoxFMNum")
        self.labelFMNo = QtWidgets.QLabel(self.groupBoxCommandButton)
        self.labelFMNo.setGeometry(QtCore.QRect(30, 210, 111, 16))
        self.labelFMNo.setObjectName("labelFMNo")
        self.pushButtonShowModSum = QtWidgets.QPushButton(self.groupBoxCommandButton)
        self.pushButtonShowModSum.setGeometry(QtCore.QRect(30, 100, 151, 31))
        self.pushButtonShowModSum.setObjectName("pushButtonShowModSum")
        self.pushButtonShowFandB = QtWidgets.QPushButton(self.groupBoxCommandButton)
        self.pushButtonShowFandB.setGeometry(QtCore.QRect(30, 280, 151, 31))
        self.pushButtonShowFandB.setObjectName("pushButtonShowFandB")
        self.labelFileLocation = QtWidgets.QLabel(self.tabTestPhase)
        self.labelFileLocation.setGeometry(QtCore.QRect(10, 690, 91, 21))
        self.labelFileLocation.setAutoFillBackground(True)
        self.labelFileLocation.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFileLocation.setObjectName("labelFileLocation")
        self.labelGetFilenameLocation = QtWidgets.QLabel(self.tabTestPhase)
        self.labelGetFilenameLocation.setGeometry(QtCore.QRect(110, 690, 1021, 21))
        self.labelGetFilenameLocation.setAutoFillBackground(True)
        self.labelGetFilenameLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGetFilenameLocation.setObjectName("labelGetFilenameLocation")
        self.groupBoxActual = QtWidgets.QGroupBox(self.tabTestPhase)
        self.groupBoxActual.setGeometry(QtCore.QRect(1140, 320, 211, 81))
        self.groupBoxActual.setStyleSheet("")
        self.groupBoxActual.setObjectName("groupBoxActual")
        self.labelGradeActual = QtWidgets.QLabel(self.groupBoxActual)
        self.labelGradeActual.setGeometry(QtCore.QRect(20, 30, 171, 31))
        self.labelGradeActual.setToolTipDuration(1)
        self.labelGradeActual.setAutoFillBackground(True)
        self.labelGradeActual.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGradeActual.setObjectName("labelGradeActual")
        self.tabWidgetTest.addTab(self.tabTestPhase, "")
        self.tabTrainPhase = QtWidgets.QWidget()
        self.tabTrainPhase.setObjectName("tabTrainPhase")
        self.pushButtonLoadFileDirectoryOfImages = QtWidgets.QPushButton(self.tabTrainPhase)
        self.pushButtonLoadFileDirectoryOfImages.setGeometry(QtCore.QRect(280, 250, 161, 31))
        self.pushButtonLoadFileDirectoryOfImages.setObjectName("pushButtonLoadFileDirectoryOfImages")
        self.labelTrainingStatus = QtWidgets.QLabel(self.tabTrainPhase)
        self.labelTrainingStatus.setGeometry(QtCore.QRect(90, 340, 91, 31))
        self.labelTrainingStatus.setObjectName("labelTrainingStatus")
        self.labelNoOfEpochs = QtWidgets.QLabel(self.tabTrainPhase)
        self.labelNoOfEpochs.setGeometry(QtCore.QRect(310, 50, 111, 31))
        self.labelNoOfEpochs.setObjectName("labelNoOfEpochs")
        self.textEditNoOfEpochs = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textEditNoOfEpochs.setEnabled(True)
        self.textEditNoOfEpochs.setGeometry(QtCore.QRect(400, 50, 141, 31))
        self.textEditNoOfEpochs.setObjectName("textEditNoOfEpochs")
        self.labelNoOfBatchSize = QtWidgets.QLabel(self.tabTrainPhase)
        self.labelNoOfBatchSize.setGeometry(QtCore.QRect(330, 120, 71, 31))
        self.labelNoOfBatchSize.setObjectName("labelNoOfBatchSize")
        self.textEditNoOfBatchSize = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textEditNoOfBatchSize.setGeometry(QtCore.QRect(400, 120, 141, 31))
        self.textEditNoOfBatchSize.setObjectName("textEditNoOfBatchSize")
        self.labelIniLearningRate = QtWidgets.QLabel(self.tabTrainPhase)
        self.labelIniLearningRate.setGeometry(QtCore.QRect(760, 50, 121, 31))
        self.labelIniLearningRate.setObjectName("labelIniLearningRate")
        self.textEditIniatialLearningRate = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textEditIniatialLearningRate.setEnabled(False)
        self.textEditIniatialLearningRate.setGeometry(QtCore.QRect(890, 50, 141, 31))
        self.textEditIniatialLearningRate.setObjectName("textEditIniatialLearningRate")
        self.textEditFileDirectoryOfImages = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textEditFileDirectoryOfImages.setEnabled(False)
        self.textEditFileDirectoryOfImages.setGeometry(QtCore.QRect(460, 250, 621, 31))
        self.textEditFileDirectoryOfImages.setObjectName("textEditFileDirectoryOfImages")
        self.labelImageDimension = QtWidgets.QLabel(self.tabTrainPhase)
        self.labelImageDimension.setGeometry(QtCore.QRect(780, 120, 121, 31))
        self.labelImageDimension.setObjectName("labelImageDimension")
        self.textImageDimension = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textImageDimension.setEnabled(False)
        self.textImageDimension.setGeometry(QtCore.QRect(890, 120, 141, 31))
        self.textImageDimension.setObjectName("textImageDimension")
        self.pushButtonStartTraining = QtWidgets.QPushButton(self.tabTrainPhase)
        self.pushButtonStartTraining.setGeometry(QtCore.QRect(540, 310, 161, 31))
        self.pushButtonStartTraining.setObjectName("pushButtonStartTraining")
        self.pushButtonStopTraining = QtWidgets.QPushButton(self.tabTrainPhase)
        self.pushButtonStopTraining.setGeometry(QtCore.QRect(730, 310, 161, 31))
        self.pushButtonStopTraining.setObjectName("pushButtonStopTraining")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(90, 370, 1181, 331))
        self.textEdit_2.setObjectName("textEdit_2")
        self.labelNoOfImages = QtWidgets.QLabel(self.tabTrainPhase)
        self.labelNoOfImages.setGeometry(QtCore.QRect(720, 190, 161, 31))
        self.labelNoOfImages.setObjectName("labelNoOfImages")
        self.textNoOfImages_2 = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textNoOfImages_2.setEnabled(False)
        self.textNoOfImages_2.setGeometry(QtCore.QRect(890, 190, 141, 31))
        self.textNoOfImages_2.setObjectName("textNoOfImages_2")
        self.textNoOfRandomSeed = QtWidgets.QTextEdit(self.tabTrainPhase)
        self.textNoOfRandomSeed.setEnabled(True)
        self.textNoOfRandomSeed.setGeometry(QtCore.QRect(400, 180, 141, 31))
        self.textNoOfRandomSeed.setObjectName("textNoOfRandomSeed")
        self.labelNoOfRandomSeed = QtWidgets.QLabel(self.tabTrainPhase)
        self.labelNoOfRandomSeed.setGeometry(QtCore.QRect(270, 180, 121, 31))
        self.labelNoOfRandomSeed.setObjectName("labelNoOfRandomSeed")
        self.tabWidgetTest.addTab(self.tabTrainPhase, "")
        self.tabAbout = QtWidgets.QWidget()
        self.tabAbout.setObjectName("tabAbout")
        self.groupBoxAFGCS = QtWidgets.QGroupBox(self.tabAbout)
        self.groupBoxAFGCS.setGeometry(QtCore.QRect(760, 180, 221, 151))
        self.groupBoxAFGCS.setAutoFillBackground(False)
        self.groupBoxAFGCS.setObjectName("groupBoxAFGCS")
        self.label_4 = QtWidgets.QLabel(self.groupBoxAFGCS)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 171, 101))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.labelLogo = QtWidgets.QLabel(self.tabAbout)
        self.labelLogo.setGeometry(QtCore.QRect(460, 140, 231, 221))
        self.labelLogo.setAutoFillBackground(False)
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("uiComponents/uiLogo.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.groupBoxDescription = QtWidgets.QGroupBox(self.tabAbout)
        self.groupBoxDescription.setGeometry(QtCore.QRect(380, 400, 721, 161))
        self.groupBoxDescription.setAutoFillBackground(False)
        self.groupBoxDescription.setObjectName("groupBoxDescription")
        self.label_5 = QtWidgets.QLabel(self.groupBoxDescription)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 681, 121))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setObjectName("label_5")
        self.tabWidgetTest.addTab(self.tabAbout, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidgetTest.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Abaca Fiber Grade Classifier"))
        self.groupBoxPrediction.setTitle(_translate("MainWindow", " Prediction Grade Labels"))
        self.labelGradePrediction1.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePercentage1.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePrediction2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePercentage2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePrediction3.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePercentage3.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePrediction4.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePercentage4.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePrediction5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePrediction6.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePercentage5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePercentage6.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePrediction7.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelGradePercentage7.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBoxCommandButton.setTitle(_translate("MainWindow", "Command Buttons"))
        self.pushButtonLoadImageFile.setText(_translate("MainWindow", "Load Image File"))
        self.pushButtonPredictImageFile.setText(_translate("MainWindow", "Predict Grade"))
        self.pushButtonShowFMs.setText(_translate("MainWindow", "Show Output Feature Maps"))
        self.labelLNo.setText(_translate("MainWindow", "Layer Number:"))
        self.pushButtonShowFM.setText(_translate("MainWindow", "Show Specific Feature Map"))
        self.labelFMNo.setText(_translate("MainWindow", "Feature Map Number:"))
        self.pushButtonShowModSum.setText(_translate("MainWindow", "Show Model Summary"))
        self.pushButtonShowFandB.setText(_translate("MainWindow", "Show Specific Filter and Bias"))
        self.labelFileLocation.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">File Location:</span></p></body></html>"))
        self.labelGetFilenameLocation.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBoxActual.setTitle(_translate("MainWindow", "Actual Grade Label"))
        self.labelGradeActual.setToolTip(_translate("MainWindow", "Actual Grade of the image classify by Mr. Ariel C. Cinco"))
        self.labelGradeActual.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\"></span></p></body></html>"))
        self.tabWidgetTest.setTabText(self.tabWidgetTest.indexOf(self.tabTestPhase), _translate("MainWindow", "Test"))
        self.pushButtonLoadFileDirectoryOfImages.setText(_translate("MainWindow", "Load Image File Directory"))
        self.labelTrainingStatus.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Training Status:</span></p></body></html>"))
        self.labelNoOfEpochs.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">No. of Epochs:</span></p></body></html>"))
        self.textEditNoOfEpochs.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">100</span></p></body></html>"))
        self.labelNoOfBatchSize.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Batch Size:</span></p></body></html>"))
        self.textEditNoOfBatchSize.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">32</span></p></body></html>"))
        self.labelIniLearningRate.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Initial Learning Rate:</span></p></body></html>"))
        self.textEditIniatialLearningRate.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">1e-3</span></p></body></html>"))
        self.textEditFileDirectoryOfImages.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">  </span></p></body></html>"))
        self.labelImageDimension.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Image Dimension:</span></p></body></html>"))
        self.textImageDimension.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">(112, 112, 3)</span></p></body></html>"))
        self.pushButtonStartTraining.setText(_translate("MainWindow", "Start Training"))
        self.pushButtonStopTraining.setText(_translate("MainWindow", "Stop Training"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.labelNoOfImages.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of Trained Images:</span></p></body></html>"))
        self.textNoOfImages_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">####</span></p></body></html>"))
        self.textNoOfRandomSeed.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">42</span></p></body></html>"))
        self.labelNoOfRandomSeed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Random Seed Start:</span></p></body></html>"))
        self.tabWidgetTest.setTabText(self.tabWidgetTest.indexOf(self.tabTrainPhase), _translate("MainWindow", "Train"))
        self.groupBoxAFGCS.setTitle(_translate("MainWindow", "Abaca Fiber Grade Classifier"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><br/>Author: Neptali E. Montanez</p><p>Adviser: Jomari Joseph A. Barrera</p><p>Date: August 2018 - June 2019</p><p>Version: 1.0.0</p><p><br/></p></body></html>"))
        self.groupBoxDescription.setTitle(_translate("MainWindow", "Description"))
        self.label_5.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:40px;\"><span style=\" font-size:10pt;\">This program automate the grading classification of Abaca fiber based on the Philippine Fiber Industry Develop-<br />ment Authority (PhilFIDA) classification using a customize VGGNet-16 Convolutional Neural Network (CNN) Architecture.<br />However, it is still recommended for actual implementation of VGGNet-16 CNN architecture in high-end PC equip with <br />GPU processors for high classification accuracy. </span><br /></p></body></html>"))
        self.tabWidgetTest.setTabText(self.tabWidgetTest.indexOf(self.tabAbout), _translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

